version: '3.8'
services:
  elasticsearch:
    image: elasticsearch:8.13.3
    environment:
      - discovery.type=single-node
      - validate_after_inactivity=0
      - max_open_files=65536
      - max_content_length_in_bytes=100000000
      - transport.host=elasticsearch
      - xpack.security.enabled=false
    volumes:
      - $HOME/app:/var/app
    ports:
      - "9200:9200"
  postgres:
    image: postgres:latest
    container_name: movie-app-db
    environment:
      - POSTGRES_DB=my-db
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=khadija
    ports:
      - "5435:5432"
    restart: always
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.13.0
#    environment:
#      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

